### ISSUE TITLE
Hebrew language is messed up in Firefox, Safari

### ISSUE THREAD

**Issue by drehelis** [badges/shields#10109]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Safari (text is mirrored) -
![image](https://github.com/badges/shields/assets/11921235/460b9e35-e5ca-4cf3-8986-0506528860e9)

Firefox -
![image](https://github.com/badges/shields/assets/11921235/44c31216-3887-4819-863f-8b4d81cd2c37)

However, works as expeced in Chrome, Chromium, Edge.
![image](https://github.com/badges/shields/assets/11921235/47194e65-15d0-402d-9db0-2b653ca03741)

Anyway to make it work? :)

### 🔗 Link to the badge

https://img.shields.io/endpoint?color=neon&style=plastic&url=https%3A%2F%2Ftg.sumanjay.workers.dev%2Fsammy_ofer_notification_channel

**Comment by chris48s** [comment]
Hmm.
I get the same behaviour as you. I suspect this is about what fonts are available on the client side.
If I view a badge in chromium, the badge is rendered using DejaVu Sans for me.
In firefox, it looks like it is falling back to the default sans serif font.
I wouldn't be able to test safari.
I'm not sure why the subset of fonts available to firefox is different here. Not sure if this is a browser thing, or if there is anything we can do.

**Comment by jNullj** [comment]
Native Hebrew speaker here, so i gave it a try.
Tested in Firefox only as i don't have Safari.
1. Changed the font yet it did not change the issue.
2. The text is squashed due to the `textLength` attribute. When the attribute is changed the text is getting spaced. Made sure both browsers default units are in px, yet i see the difference.
3. After playing a bit with `textLength` i found out this! The value we use in this example is `2250`. This is squashed. So i increased to make it more spaced out, which works but it was reversed regardless of the `direction` attribute. (4500 is a bit shorter then 2250 on chromium). Untill, i used `textLength=890` then the letter order was currect and it started getting spaced out the _smaller_ i made the textLength.
4. I then went to test `textLength` in an example on [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength) and confirmed that this is not related to shields.io but a firefox issue. Here is a short animation to show how the mmdn docs example starts breaking once the text is hebrew instead of English. I suspect the length calculated for each letter is somehow a negative value as the 0px behavior is rendered at large values (620px~ in the example bellow).
Video taken from [this part in mdn web docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength#result) replaced the innerHtml with herbew for hello world.

https://github.com/badges/shields/assets/15849761/5b5adeff-dc07-44c1-ae03-90b277f6fbf7

The text acts odd, the 0 point for textLength is about 620px and after crossing it the text is reveresed, before crossing it lower values create higher length.

**Comment by jNullj** [comment]
I think i found the bug, gonna open a pull request for Firefox

**Comment by PyvesB** [comment]
@jNullj what is the status of this issue, did you get this fixed in Firefox in the end?

**Comment by jNullj** [comment]
Hey, this one got under my radar.

I worked on this for some time and was able to fix the issue, but due to some oddities of FireFox with RTL, the fix introduced new issues.
I ended up putting this on hold as I worked on a really low end machine and this made it very hard to debug.

I lost track of this issue and ended up with a half baked solution on one hand and no open ticket on mozila's bug tracker on the other.

I might take a new look this week, both search if an issue is open, and also migrate my old code to my new machine and recreate a dev env for this there

They finally made the switch to git, this is a bit encouraging.

**Comment by drehelis** [comment]
Firefox 148.0.2 (aarch64) issue still exists
So is Safari Version 26.2

**Comment by jNullj** [comment]
Sadly i was not able to fix this in firefox yet. i did find the source of the issue in the source code so far.
Did not look into safari, you may want to open an issue upstream regarding the issue with Safari.
