### ISSUE TITLE
NuGet badges don't work for SemVer 2 packages

### ISSUE THREAD

**Issue by onovotny** [badges/shields#1044]
Might be related to use of the v3 endpoint or not (or possibly just needing to add the right semverlevel=2.0.0 query parameter), but badges for SemVer 2 packages aren't currently working.

https://github.com/badges/shields/issues/655

https://img.shields.io/nuget/vpre/RSAKeyVaultProvider.svg
https://www.nuget.org/packages/RSAKeyVaultProvider

See https://github.com/NuGet/Home/wiki/Semver-2.0.0-Protocol for the protocol support update. Needs an additional query parameter to return semVer 2.0 packages.

**Comment by paulmelnikow** [comment]
Hi! I'm seeing `nuget | v1.0.1` which matches the website, so it looks like this has been fixed. If not, feel free to reopen or comment.

**Comment by onovotny** [comment]
That's because I released a stable package.

**Comment by onovotny** [comment]
The key is that you have to add `semVer=2.0.0` as a query string parameter to however you're getting the version list.

**Comment by kzu** [comment]
This is still not fixed, not even for stable packages, if they use semver2. See https://img.shields.io/nuget/v/InjectModuleInitializer.svg vs https://www.nuget.org/packages/InjectModuleInitializer. 2.0.0 is the latest stable, but the shield shows 1.5.0 instead, which is the last one that did *not* use semver2.
