### ISSUE TITLE
Better license shields

### ISSUE THREAD

**Issue by KOLANICH** [badges/shields#1093]
1 Open https://tldrlegal.com/license/apache-license-2.0-(apache-2.0) .
Look at the page.
You see 3 columns of different colors. Each column has clauses describing license in short, each clause has own pictogram.
2 [GitHub has an API](https://developer.github.com/v3/licenses/) returning the similar information.

So, how should the license shield look like?
 0 Background color: 
  * red for proprietary or missing (which makes the work automatically proprietary)
  * orange for unrecognized (the license doesn't look like proprietary, but it is not in the database)
  * yellow for viral (aka copyleft, like GPL and MPL)
  * cyan for permissive (Apache, MIT, BSD)
  * bright green for public-domain like (Unlicense, CC-0, WTFPL)
 1 a logo: #1219
 2 a SPDX identifier
 3 areas of pictograms, each area has own background color,  and contains pictogramms matching the corresponding column of tldrlegal. Of course you'll have to find own source of icons since tldrlegal's ones are copyrighted and not in svg.

**Comment by paulmelnikow** [comment]
I like the idea of colors! Probably I would make the unrecognized license either gray, which we usually use for unknown, or red, since some rando license is not so safe, and might even be proprietary.

**Comment by KOLANICH** [comment]
unrecognized license may be proprietary, so orange

**Comment by ritwickdey** [comment]
I like the idea too 👍 . I think we have to sort the all licence -- but is it not huge? -- I don't know.

**Comment by KOLANICH** [comment]
>sort all the license

tldrlegal and github have done the work for you. You only need to get the data through API and draw a shield

**Comment by ritwickdey** [comment]
from github, i can find only these -

```js
  "agpl-3.0",
  "lgpl-3.0",
  "bsd-2-clause",
  "epl-1.0",
  "bsd-3-clause",
  "gpl-2.0",
  "mpl-2.0",
  "mit",
  "gpl-3.0",
  "lgpl-2.1",
  "unlicense",
  "apache-2.0"
```

**Comment by platan** [comment]
I will implement this improvement.

**Comment by paulmelnikow** [comment]
Addressed in #1190! Though perhaps we should leave this open until we apply these changes to the rest of the license badges.

**Comment by KOLANICH** [comment]
The rest of thingsm like icons for clauses are still not implemented.

**Comment by paulmelnikow** [comment]
There's been some discussion of license colors in #2026 so let's finish that discussion there.

By default, we don't show icons on badges; that's something users can opt into.
