### ISSUE TITLE
Show the complete list of supported logos in the frontend

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3658]
:clipboard: **Description**

Let's provide at least a simple page of all the supported logo slugs.

We could also print the list of simple-icons that's deployed, as an additional cross-reference, and mention that we merge updates roughly every Monday and ship within a few days of that.

It'd be _even cooler_ to add a logo picker, though a list would suffice 😀 

Ref #3639 #3297 #2980

**Comment by chris48s** [comment]
You already did this: https://github.com/badges/shields/pull/2890

but its disabled in production because if a user tries to load it, it immediately bans their IP

Probably the job here is to see if we can find a way to render something that does that job in a way that doesn't make >1,000 requests to render the page :)

**Comment by paulmelnikow** [comment]
Ha! 

> Probably the job here is to see if we can find a way to render something that does that job in a way that doesn't make >1,000 requests to render the page :)

Yea. I suppose we can leave off the previews, which should solve it. Or maybe load the images right from simple-icons instead of showing 'em on a badge.

**Comment by chris48s** [comment]
I think I'm pretty happy with this way this is currently handled (with links out to https://simpleicons.org/ and https://github.com/simple-icons/simple-icons/blob/master/slugs.md ).

We could still consider a picker. The full SimpleIcons set is now too big for that to be something simple like a dropdown menu. It would have to be some kind of search interface.

**Comment by calebcartwright** [comment]
I'll add that I'm content with linking out as well. I know we still get the occasional question in some form of "what exactly should the slug be for this?", but my gut position remains that it's reasonable for us to point folks to the authoritative source.

I admit this is probably just another reflection of my philosophy that we shouldn't have to do _too_ much on behalf of the user to help them do a (typically) one-time exercise of constructing their badge url.

**Comment by uncenter** [comment]
I 100% agree we should stick to linking out and I don't even think we should consider making our own logo picker - the [Simple Icons website](https://simpleicons.org/) already has this feature as you mentioned and it is pointless for us to duplicate it when we can just send users there.

**Comment by PyvesB** [comment]
Agreed that linking as we currently do is the best approach here. Will go ahead and close this issue.
