### ISSUE TITLE
Node.js version for scoped packages seams broken

### ISSUE THREAD

**Issue by Starefossen** [badges/shields#723]
Node.js version for scoped packages seams to be broken, it works for non-scoped packages through.

| Package | Scope | Badge |
| --- | --- | --- |
| `express` | not scoped | ![](https://img.shields.io/node/v/express.svg?maxAge=2592000) |
| `@cycle/core` | scoped | ![](https://img.shields.io/node/v/@cycle/core.svg?maxAge=2592000) |

The package `@cycle/core` does in fact have a Node.s version specified in [their package.json](https://github.com/cyclejs/core/blob/master/package.json#L43).

**Comment by paulmelnikow** [comment]
Related: #925, #926, #757, #796

**Comment by kgryte** [comment]
@paulmelnikow Is anything blocking this from being resolved?

**Comment by paulmelnikow** [comment]
Seems it was fixed in #926!

**Comment by kgryte** [comment]
@paulmelnikow That is incorrect. It was not fixed. Navigate to https://img.shields.io/node/v/@cycle/core.svg and you will see that the version is not displayed.

For another example, navigate to https://img.shields.io/node/v/@stdlib/stdlib.svg.

**Comment by paulmelnikow** [comment]
Gotcha. It's the **Node** version, not the package version.

Would you like to work up a PR based on the work in #926?

**Comment by kgryte** [comment]
Sure. I will take a look at it later tonight.

**Comment by kgryte** [comment]
@paulmelnikow PR submitted. See #1084.
