### ISSUE TITLE
chrome web store badges failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9965]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All chrome web store badges failing - underlying error is `FetchError: maximum redirect reached`

/cc @ParticleCore

### 🔗 Link to the badge

https://img.shields.io/chrome-web-store/rating/ogffaloegjglncjfehdfplabnoondfjo

### 💡 Possible Solution

We interact with chrome web store via a package: https://www.npmjs.com/package/webextension-store-meta

As a starting point I've raised an issue upstream at https://github.com/awesome-webextension/webextension-store-meta/issues/2

We might need to look into contributing a fix to the upstream lib ourselves. I guess something has changed in chrome web store itself that needs accounting for when we call it :crossed_fingers:

**Comment by mnoorenberghe** [comment]
> I guess something has changed in chrome web store itself that needs accounting for when we call it

A major [redesign and domain change was released](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/9lc7Prf9vLk/m/fmsUd2LZAQAJ)

**Comment by chris48s** [comment]
Most of these are fixed (users, version, rating, etc), but we had to drop the price badges as the data is no longer available.

**Comment by sinsinpub** [comment]
it seems be still failing for some extensions?
https://img.shields.io/chrome-web-store/stars/hkgmldnainaglpjngpajnnjfhpdjkohh
![image](https://github.com/badges/shields/assets/160240/e5bf3dad-524b-4476-bb20-41d9e8854f28)
got `inaccessible`, have to grunt something in webstore side settings?

**Comment by ParticleCore** [comment]
> it seems be still failing for some extensions? https://img.shields.io/chrome-web-store/stars/hkgmldnainaglpjngpajnnjfhpdjkohh ![image](https://private-user-images.githubusercontent.com/160240/308208245-e5bf3dad-524b-4476-bb20-41d9e8854f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDkxNjYsIm5iZiI6MTcwOTA0ODg2NiwicGF0aCI6Ii8xNjAyNDAvMzA4MjA4MjQ1LWU1YmYzZGFkLTUyNGItNDQ3Ni1iYjIwLTQxZDllODg1NGYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNTQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTgzMDAwNWM4NmExNmZlYzhhZjlhYzAwMTlkMzE3ZTA4MWVmYmYxY2FmZTI4MzhjMjE5YzJhMDQ4NjQwZmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s3UDJlX6TYDbhpMPixsyc3eJKX6OQYX2XR2d5MkrFe8) got `inaccessible`, have to grant some permission thingy in webstore side settings?

I imagine it might be having trouble with the extension name containing a special character (`改`) in the url: https://chromewebstore.google.com/detail/kancolle-command-center-改/hkgmldnainaglpjngpajnnjfhpdjkohh

**Comment by chris48s** [comment]
@sinsinpub I've raised this upstream https://github.com/awesome-webextension/webextension-store-meta/issues/2#issuecomment-1967382590

**Comment by sinsinpub** [comment]
> > it seems be still failing for some extensions? https://img.shields.io/chrome-web-store/stars/hkgmldnainaglpjngpajnnjfhpdjkohh ![image](https://private-user-images.githubusercontent.com/160240/308208245-e5bf3dad-524b-4476-bb20-41d9e8854f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDkxNjYsIm5iZiI6MTcwOTA0ODg2NiwicGF0aCI6Ii8xNjAyNDAvMzA4MjA4MjQ1LWU1YmYzZGFkLTUyNGItNDQ3Ni1iYjIwLTQxZDllODg1NGYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNTQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTgzMDAwNWM4NmExNmZlYzhhZjlhYzAwMTlkMzE3ZTA4MWVmYmYxY2FmZTI4MzhjMjE5YzJhMDQ4NjQwZmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s3UDJlX6TYDbhpMPixsyc3eJKX6OQYX2XR2d5MkrFe8) got `inaccessible`, have to grant some permission thingy in webstore side settings?
> 
> I imagine it might be having trouble with the extension name containing a special character (`改`) in the url: [https://chromewebstore.google.com/detail/kancolle-command-center-改/hkgmldnainaglpjngpajnnjfhpdjkohh](https://chromewebstore.google.com/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh)

yea, might be a case. have tried servral extensions with CJK character name, got the same issue. some handling of url encoding/deocoding needed for upstream?

**Comment by xmcp** [comment]
Hi, I have recently [fixed the FetchError issue with non-ASCII characters](https://github.com/awesome-webextension/webextension-store-meta/issues/2) in the upstream `webextension-store-meta` library, and the patch is included in its v1.2.0 version. This version should fix the issue.
